# Generated by Django 6.0.6 on 2026-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeinXOEVStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieferant', models.CharField(max_length=200)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=15)),
                ('stueckzahl', models.IntegerField()),
            ],
        ),
    ]
